version: '3'

services:
  app:
    container_name: product-list-app
    build: .
    ports:
      - '5000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/build
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CI=true
